import placeholder from "./public/placeholder.svg";
const placeholderUrl = typeof placeholder === "string" ? placeholder : (placeholder && placeholder.src) ? placeholder.src : placeholder;

export const teamMembers = [
  //CORE COMMITEE
  {
    id: 1,
    name: "Gayati Umap",
    position: "SECRETARY",
    imageUrl: "https://drive.google.com/open?id=1XA8NIrILPIDOkOO_32IjvQJlyQ3jzqpu",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/gayatri-umap/",
    githubUrl: "https://github.com/gayatriumap19", 
  },
  {
    id: 2,
    name: "Tiya Banerjee",
    position: "JOINT SECRETARY",
    imageUrl: "https://drive.google.com/open?id=19ludNP0F8xsJGLIF8W14eh2UkhflcLZe",
    instagramUrl: "https://www.instagram.com/tiyabanerjee_?igsh=ZzZkcTdzNm14ODkw",
    linkedinUrl: "https://www.linkedin.com/in/tiya-banerjee",
    githubUrl: "", 
  },
  {
    id: 41,
    name: "Alok Roy",
    position: "TREASURER",
    imageUrl: "https://drive.google.com/open?id=1dChKHKnL3dJkTs2nrxEHJ7ZbSt4BDXgD",
    instagramUrl: "https://www.instagram.com/alokproy",
    linkedinUrl: "https://in.linkedin.com/in/alok-roy-",
    githubUrl: "https://github.com/AlokRoyal",
  },
  {
    id: 42,
    name: "Aditya Chafale",
    position: "JOINT SECRETARY",
    imageUrl: "https://drive.google.com/open?id=1elEY_3g3t3Ly_F1YIwzkrhqBcgIOo_nK",
    instagramUrl: "https://www.instagram.com/aditya_chafale_?igsh=MXh5dmM3d3RzenBlNg==",
    linkedinUrl: "https://www.linkedin.com/in/aditya-chafale-34332228b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },
  {
    id: 43,
    name: "Dishita Ghuge",
    position: "JOINT TREASURER",
    imageUrl: "https://drive.google.com/open?id=1jYVGe6cJxYesNlmHSC3RQ1eON3lknbiN",
    instagramUrl: "https://www.instagram.com/dishitaghuge_?igsh=MTE1NjFnODM5d3NxeA%3D%3D&utm_source=qr",
    linkedinUrl: "https://www.linkedin.com/in/dishita-ghuge-79a67b2a5?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "https://github.com/dishitaghuge01",
  },
// TECHNICAL TEAM
  {
    id: 25,
    name: "Laukik Lanje",
    position: "TECHNICAL HEAD",
    imageUrl: "https://drive.google.com/open?id=1iL-IfmBKRLPmzftYiuB6IG0217q59OEV",
    instagramUrl: "https://www.instagram.com/laukik2404?igsh=OWhlZm4xaXljdXJi",
    linkedinUrl: "https://www.linkedin.com/in/laukik-lanje?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "https://github.com/laukik-24",
  },
  {
    id: 26,
    name: "Mehul Kohad",
    position: "TECHNICAL HEAD",
    imageUrl: "https://drive.google.com/open?id=1OC4S_hWMaCYMXUcFSD_zCbahuhGVN7_D",
    instagramUrl: "https://www.instagram.com/mehulkohad?igsh=amgzYWxuZW1qOWN4",
    linkedinUrl: "http://linkedin.com/in/mehul-kohad",
    githubUrl: "https://github.com/mehul515",
  },
  {
    id: 27,
    name: "Lokesh Parate",
    position: "TECHNICAL HEAD",
    imageUrl: "https://drive.google.com/open?id=15r52gtST3KflLPlwIm1-5CIOofm94wKz",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/lokesh-parate-08a70b256",
    githubUrl: "https://github.com/supremeStrange-04",
  },
  {
    id: 3,
    name: "Himanshu Chavan",
    position: "WEB MASTERS",
  imageUrl: "https://drive.google.com/open?id=1qVFScbM_saD_wXPu9GI2mYNKE6G73Reu",
    instagramUrl: "https://www.instagram.com/himanshuchavan98?igsh=MWxvdDY5Z2dycjAwbw==",
    linkedinUrl: "https://www.linkedin.com/in/himanshu-chavan-1a0b5330a/",
    githubUrl: "https://github.com/Himanshujchavan"
  },
  {
    id: 4,
    name: "Akanksha Sawant",
    position: "WEB MASTERS",
  imageUrl: "https://drive.google.com/open?id=16XE3CHBgQafYN1DishWb-AcvJt4kZ1v_",
  instagramUrl: "",
  linkedinUrl: "https://www.linkedin.com/in/akanksha-sawant-2598a1305",
  githubUrl: "https://github.com/nastyax0"
  },
  {
    id: 5,
    name: "Atul Thakre",
    position: "WEB MASTERS",
  imageUrl:"https://drive.google.com/open?id=1YxYJ-dNXRS5OxiGjYgDIkPW3H6eC3zQn",
  instagramUrl: "",
  linkedinUrl: "https://www.linkedin.com/in/atul-thakre-logers?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  githubUrl: "https://github.com/Atul-ThakreLO"
  },
  {
    id: 45,
    name: "Saksham Khobragade",
    position: "TECHNICAL CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1v-_ErhWwe5zcQgXxbiSTSPRxPuJ0uCmZ",
    instagramUrl: "https://www.instagram.com/skshm_sk?igsh=MXhnaTNjNXp1OTA4bw==",
    linkedinUrl: "https://www.linkedin.com/in/saksham-khobragade-a421112b7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "https://github.com/Sakshamk17",
  },
  {
    id: 46,
    name: "Rishabh Gokhe",
    position: "TECHNICAL CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1dx1mw0MUACtEaj46ll6T98gSC8UGsJfb",
    instagramUrl: "https://www.instagram.com/rishabh_gokhe/",
    linkedinUrl: "https://www.linkedin.com/in/rishabh-gokhe",
    githubUrl: "https://github.com/rishabhgokhe",
  },
   {
    id: 61,
    name: "Yogesh Nagrare",
    position: "TECHNICAL MEMBER",
    imageUrl: "https://drive.google.com/open?id=1tdPlxTc24mFFFJAHSYOlqYX-7n-akXfD",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/yogesh-nagrare-707a9b32a/",
    githubUrl: "https://github.com/Yogesh-Nagrare",
  },
  // EVENT MANAGEMENT Team
    {
    id: 35,
    name: "Mandar Lakhe",
    position: "E M HEAD",
    imageUrl: "https://drive.google.com/open?id=1PJzWXZJE0X-NpL8i2RPFz7fOMgqECkOx",
    instagramUrl: "",
    linkedinUrl: "",
    githubUrl: "",
  },
    {
    id: 39,
    name: "Kushal Javkhedkar",
    position: "H M HEAD",
    imageUrl: "https://drive.google.com/open?id=1cUTcHS_MC4vVg08yoDBn0twLAHI11J1r",
    instagramUrl: "https://www.instagram.com/kushal.javkhedkar?igsh=NGZpM3MxZndkZ21x",
    linkedinUrl: "https://www.linkedin.com/in/kushal-nitin-javkhedkar-85813a327?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },
  {
    id: 6,
    name: "Rohan Andelkar",
    position: "E M MASTERS",
  imageUrl: "https://drive.google.com/open?id=1yutzO-ZgAahmexahgfvqWzUat0gdpHJj",
  instagramUrl: "https://www.instagram.com/rohan___jills?igsh=MWV2bXVlM3RlNmhj",
  linkedinUrl: "https://www.linkedin.com/in/rohanandelkar?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  githubUrl: "https://github.com/rohanandelkar"  
},
  {
    id: 7,
    name: "Aditya Mendhe",
    position: "E M MASTERS",
  imageUrl:"https://drive.google.com/open?id=1dCgyv_WwKNuiYlHV2JHPp6AS6nAAIPdJ",
  instagramUrl: "https://www.instagram.com/aditya_mendhe29",
  linkedinUrl: "https://www.linkedin.com/in/aditya-mendhe-869896282?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  githubUrl: "https://github.com/Aditya125-cell"
  },
  {
    id: 8,
    name: "Achal Shahu",
    position: "E M MASTERS",
  imageUrl: "https://drive.google.com/open?id=1Hs0kYeBLMQAbhIjGz_kyDLCzY49gQTdR",
  instagramUrl: "https://www.instagram.com/achallll.04?igsh=MXV0a2l1aTdzdjV3bQ==",
  linkedinUrl: "https://www.linkedin.com/in/achal-sahu-480891284?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  githubUrl: ""
  },
  {
    id: 9,
    name: "Vedant Bomidwar",
    position: "E M MASTERS",
  imageUrl: "https://drive.google.com/open?id=1V7PhSaedfMEcPOBGLg_HZbHPDFqeJ_4d",
  instagramUrl: "https://www.instagram.com/vedant_b04?igsh=MWRnemh1NGNuOHhqMA==",
  linkedinUrl: "https://www.linkedin.com/in/vedantbomidwar",
  githubUrl: "https://github.com/Vedantb04",
  },
{
    id: 53,
    name: "Aditya Tekade",
    position: "EVENT MANAGEMENT CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1YfvbnNMHAtZeLRic7feFOMKwRYoYJU__",
    instagramUrl: "https://www.instagram.com/adityatekade_18?igsh=MXRzOXY0OGh4NGcxeg==",
    linkedinUrl: "https://www.linkedin.com/in/aditya-tekade-626104287?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "https://github.com/Adityamtekade/",
  },
  {
    id: 54,
    name: "Bhavesh Doifode",
    position: "E M CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1_QhMytLvxyXUQ6Po1V28V5CaJmjxkDSR",
    instagramUrl: "https://www.instagram.com/doifode__27/profilecard/?igsh=M2xsc3I0bnFuYmR3",
    linkedinUrl: "https://www.linkedin.com/in/bhavesh-doifode-a760312a7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    githubUrl: "",
  },
   {
    id: 62,
    name: "Kripa Vazirani",
    position: "E M MEMBER",
    imageUrl: "https://drive.google.com/open?id=1O5JJKdVbwUJdwi1XvzU-GeRsh6M-L59O",
    instagramUrl: "https://www.instagram.com/kripa_vazirani12?igsh=MXhxeTA0MDV2MHI0OA%3D%3D&utm_source=qr",
    linkedinUrl: "",
    githubUrl: "",
  },
    {
    id: 66,
    name: "Diya Choudhari",
    position: "HALL MANAGEMENT",
    imageUrl: "https://drive.google.com/open?id=1Alcui7TtlXrFI1f4sz3gIE4zLhp9B8K4",
    instagramUrl: "https://www.instagram.com/diya_choudhari28/",
    linkedinUrl: "https://www.linkedin.com/in/diya-choudhari-aa5861263/",
    githubUrl: "https://github.com/Diya-Choudhari",
  },
  {
    id: 67,
    name: "Riya Singh",
    position: "H M MEMBER",
    imageUrl: "https://drive.google.com/open?id=1s6NAZKErKLL-tlf2g_Vv8IkJZsHHaenU",
    instagramUrl: "https://www.instagram.com/xoxoo_riyaa/profilecard/?igsh=ejdjbGM1OGJieHh4",
    linkedinUrl: "https://www.linkedin.com/in/riya-singh-ba2ba8345?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },
  //LITERATURE TEAM
  {
    id: 37,
    name: "Nishita Dande",
    position: "LITERATURE HEAD",
    imageUrl:"https://drive.google.com/open?id=1T5PIT5UElxL39Rs2Ex7uLJKaK3PneCtF",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/nishita-dande",
    githubUrl: "",
  },
  {
    id: 38,
    name: "Dhani Rathod",
    position: "LITERATURE HEAD",
    imageUrl:"https://drive.google.com/open?id=10fC2pBgt28wzl5YuNDW9HTPA01JWPehN",
    instagramUrl: "https://www.instagram.com/dhaniirathod?igsh=MW94cHluZGtvaGtmeA==",
    linkedinUrl: "https://www.linkedin.com/in/dhani-rathod",
    githubUrl: "https://github.com/DhaniRathod",
  },
    {
    id: 56,
    name: "Neha Dhawas",
    position: "LITERATURE CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1Kw1Cv4rVIpNkxOHX_3ihaxi4hc-iLLEr",
    instagramUrl: "https://www.instagram.com/neha._.dhawas?igsh=MXZpeHVjdXgwMjZsaA==",
    linkedinUrl: "https://www.linkedin.com/in/neha-d-22b9b6220",
    githubUrl: "",
  },
  {
    id: 10,
    name: "Himanshi  Choubal",
    position: "CONTENT CREATION MASTERS",
  imageUrl: "https://drive.google.com/open?id=1uOXn7osrQkWRoFcZkUB5dlg6smkcVW3C",
  instagramUrl: "https://www.instagram.com/himanshi_choubal?igsh=MTNodzdiZTk4MTA4Mw==",
  linkedinUrl: "https://www.linkedin.com/in/himanshi-choubal-430026299/",
  githubUrl: "",
  },
  {
    id: 11,
    name: "Granthi Kaur",
    position: "CONTENT CREATION MASTERS",
  imageUrl: "https://drive.google.com/open?id=169K7qF7rFf8Ui376Yza4B75elwntfS5I",
  instagramUrl: "",
  linkedinUrl: "",
  githubUrl: "",
  },
  {
    id: 12,
    name: "Soukhya Sasankar",
    position: "CONTENT CREATION MASTERS",
  imageUrl:"https://drive.google.com/open?id=1vv0Y1Ak3eHZU-pLAFoZz9b47o_JzOMyJ",
  instagramUrl: "",
  linkedinUrl: "https://www.linkedin.com/in/soukhya-sasankar-91080a35a",
  githubUrl: "",
  },

  // DESIGN Team
  {
    id: 13,
    name: "Aditya Rajankar",
    position: "DESIGN Head",
  imageUrl:"https://drive.google.com/open?id=1J8wpLXsVklD94t11IqbVc7bD_5oTrRgi",
  instagramUrl: "https://www.instagram.com/adityar.og/",
  linkedinUrl: "https://www.linkedin.com/in/aditya-rajankar/",
  githubUrl: "",
  },
    {
    id: 31,
    name: "Devyani Gharad",
    position: "ART HEAD",
    imageUrl: "https://drive.google.com/open?id=1_Y9yOnFDETt8phudGWK5Lts4dxiukLGR",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/devyani-gharad",
    githubUrl: "",
  },
  {
    id: 32,
    name: "Janvi Thakre",
    position: "ARTS HEAD",
    imageUrl: "https://drive.google.com/open?id=1sn_RLdbneNrFS70E3lrMRRsC4lWmP4s_",
    instagramUrl: "https://www.instagram.com/justt_janvi07?igsh=MW1sNDZlZjlvcTRmYg==",
    linkedinUrl: "http://linkedin.com/in/janvi-thakre",
    githubUrl: "https://github.com/JanviThakre",
  },
  {
    id: 14,
    name: "Divesh Kshirsagar",
    position: "DESIGN MASTERS",
  imageUrl: "https://drive.google.com/open?id=11QSL1vga8czku9RB7W_yLtNKx1hetr2c",
  instagramUrl: "https://www.instagram.com/divesh.kshirsagar?igsh=MTJlajVkOW95ZDkzdw==",
  linkedinUrl: "https://www.linkedin.com/in/divesh-kshirsagar",
  githubUrl: "https://github.com/Divesh-Kshirsagar",
  },
  {
    id: 15,
    name: "Aishwarya Khetade",
    position: "DESIGN MASTERS",
  imageUrl: "https://drive.google.com/open?id=1ypLb43Yb618K_iGFNKtx4ZvBOxzkFGQQ",
  instagramUrl: "https://www.instagram.com/aishwarya__k10?igsh=b3hqdjJlNzVyb3pk",
  linkedinUrl: "https://www.linkedin.com/in/aishwarya-khetade-8a6124253?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  githubUrl: "",
  },
   {
    id: 50,
    name: "Rohini Bhoyar",
    position: "ARTS CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1xIZJgqIbQOf7H42mrfHga76Tm8jSK43g",
    instagramUrl: "https://www.instagram.com/rohini_bhoyar_?igsh=czV6Mmp1bHFxODFq",
    linkedinUrl: "https://www.linkedin.com/in/rohini-bhoyar-08089a376?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },
  {
    id: 51,
    name: "Vaibhavi Tumsare",
    position: "ART CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1bHUd4ZSc8JaXgrbD8YlqkaD2guBB8QIm",
    instagramUrl: "https://www.instagram.com/vaibhavi.tumsare_/",
    linkedinUrl: "https://www.linkedin.com/in/vaibhavi-tumsare-40320b2b4",
    githubUrl: "https://github.com/Vaibhavitumsare",
  },
  {
    id: 16,
    name: "Shreya Sakhare",
    position: "DESIGN MASTERS",
  imageUrl: "https://drive.google.com/open?id=1oXN7zdJbFfenRednsYF0GgNgh8W56cSa",
  instagramUrl: "https://www.instagram.com/shreyasakharee?igsh=MWF1NjQzeDA3OWE0cQ==",
  linkedinUrl: "",
  githubUrl: "",
  },
   {
    id: 59,
    name: "Nicky Meshram",
    position: "DESIGN MEMBER",
    imageUrl: "https://drive.google.com/open?id=1Tw-RAwxOd6hbxyIwe8iRiLLUbVh7-eGh",
    instagramUrl: "https://www.instagram.com/nickyymeshram",
    linkedinUrl: "https://www.linkedin.com/in/nickymeshram",
    githubUrl: "https://github.com/NickyMeshram",
  },
   {
    id: 64,
    name: "Savani Apte",
    position: "Design MEMBER",
    imageUrl: "https://drive.google.com/open?id=18lti855IvUXpWkSTrq1b28b14qpcS0_T",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/savani-apte-93a882304?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },
  // PUBLICITY Team
{ 
  id: 17,
    name: "Aaditi Bedarkar ",
    position: "PR Head",
  imageUrl:"https://drive.google.com/open?id=1KUsZ9OKao6vIFBAu0C75jWZmSDKmfOnS",
  instagramUrl: "https://www.instagram.com/adityatekade_18?igsh=MXRzOXY0OGh4NGcxeg==",
  linkedinUrl: "https://www.linkedin.com/in/aditya-tekade-626104287?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  githubUrl: "https://github.com/Adityamtekade/",
  },
   {
    id: 29,
    name: "Atharva Vaidya",
    position: "PUBLICITY HEAD",
    imageUrl: "https://drive.google.com/open?id=1coKoLP9h_zeX74PAfpqHmkrEiMg2gfGB",
    instagramUrl: "https://www.instagram.com/atharva3402/",
    linkedinUrl: "http://www.linkedin.com/in/atharva-vaidya-b19b0125a",
    githubUrl: "",
  },
  {
    id: 30,
    name: "Raj Bhelkar",
    position: "PUBLICITY HEAD",
    imageUrl: "https://drive.google.com/open?id=1AmldPGtOohswY_yDt6b2yuc0YoywEhch",
    instagramUrl: "https://www.instagram.com/_rajkb?igsh=ejA0MnRoNmh5NjVm&utm_source=ig_contact_invite",
    linkedinUrl: "https://www.linkedin.com/in/raj-bhelkar-53750725a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },
  {
    id: 48,
    name: "Samiksha Bilgaye",
    position: "PUBLICITY CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1HcfWFVI27ZuCYWkyiv9ZLVCSbJlRqIaM",
    instagramUrl: "https://www.instagram.com/_.sam._1205?igsh=MXQwN2JkNmxieXd1MQ%3D%3D&utm_source=qr",
    linkedinUrl: "https://www.linkedin.com/in/samiksha-bilgaye-b91a71339?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    githubUrl: "",
  },
  {
    id: 49,
    name: "Sana Channawar",
    position: "PUBLICITY CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1cASRLuFg2Palt4Hl8oZAeQpg6yljYXEC",
    instagramUrl: "https://www.instagram.com/sana__1509?igsh=MTNxaHhwazViZGpzdA==",
    linkedinUrl: "https://www.linkedin.com/in/sana-channawar-b63a2b2b9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },

  {
    id: 18,
    name: "Neha Kotalwar",
    position: "PR MASTERS",
  imageUrl: "https://drive.google.com/open?id=1rKRY_DSoxOnNRCkLbp-lmW_RqnlgmeRv",
  instagramUrl: "",
  linkedinUrl: "https://www.linkedin.com/in/neha-kotalwar-304753274",
  githubUrl: "https://github.com/nehakotalwar",
  },

  //CULTURAL TEAM
  {
    id: 19,
    name: "Richa Kalpande",
    position: "CULTURAL HEAD",
    imageUrl: "https://drive.google.com/open?id=1owSy8jDNjFmUtT5oXkL0Za6iaLNS_-ec",
    instagramUrl: "https://www.instagram.com/richa.k23?igsh=MXBzNGFxbzNvbDNsZg==",
    linkedinUrl: "http://www.linkedin.com/in/richa-kalpande",
    githubUrl: "https://github.com/richa-k23",
  },
  {
    id: 20,
    name: "Ayush Asutkar",
    position: "CULTURAL HEAD",
    imageUrl: "https://drive.google.com/open?id=1Z-oQfgZ-MQf7dUetYlC58omBOFWaJK9n",
    instagramUrl: "",
    linkedinUrl: "",
    githubUrl: "",
  },
  {
    id: 21,
    name: "Vaishnavi Asare",
    position: "CULTURAL HEAD",
    imageUrl: "https://drive.google.com/open?id=1YRjJ2MfoqLE1nOSFnuO7ZnN1dMRS6bEo",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/vaishnavi-asare",
    githubUrl: "",
  },
  {
    id: 57,
    name: "Saee Nimbalkar",
    position: "CULTURAL CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1u-944GZWT74MSx2RKKnpFkTggQs7_OVj",
    instagramUrl: "https://www.instagram.com/saeee.nimbalkar?igsh=MWtzY3c4eW40Y3B6Mg==",
    linkedinUrl: "https://www.linkedin.com/in/saeeenimbalkar?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },



  // SPONSORSHIP TEAM
  {
    id: 28,
    name: "Darpan Thakur",
    position: "SPONSORSHIP HEAD",
    imageUrl:"https://drive.google.com/open?id=1om9cryjN7YCHI9CIpKmB7Xtp3v1xe9WJ",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/darpan-thakur",
    githubUrl: "",
  },
  {
    id: 47,
    name: "Kabeir Kaushik",
    position: "SPONSORSHIP CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1GqfX1BHey5FXu7984JGpEDhAp7mGdjFs",
    instagramUrl: "https://www.instagram.com/kabeirrr?igsh=NHhjY2dmNXd0aDZ1&utm_source=qr",
    linkedinUrl: "https://www.linkedin.com/in/kabeirkaushik",
    githubUrl: "",
  },
 {
    id: 63,
    name: "Advait Mahajan",
    position: "SPONSORSHIP MEMBER",
    imageUrl: "https://drive.google.com/open?id=1VwgQIKS7DkvE_Va5XVZrsXNNt8bH29U4",
    instagramUrl: "https://www.instagram.com/iamadvait_225",
    linkedinUrl: "https://www.linkedin.com/in/advaitmahajan255",
    githubUrl: "https://github.com/IAmAdvait",
  },

  // SOCIAL MEDIA TEAM
  {
    id: 40,
    name: "Ayush Sontakke",
    position: "SOCIAL MEDIA HEAD",
    imageUrl: "https://drive.google.com/open?id=17Ayji9KG8ov7keOXmvXk8GcV_l8mdWmZ",
    instagramUrl: "https://www.instagram.com/___ayushsontakke___09?igsh=MWVycWUxOTNkcnZzaw==",
    linkedinUrl: "https://www.linkedin.com/in/ayush-sontakke-779202280?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "",
  },
    {
    id: 58,
    name: "Disha Nannaware",
    position: "SOCIAL MEDIA CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1MrbDilOfbz5QdhLqwJMBE_l1gBkq0BAW",
    instagramUrl: "",
    linkedinUrl: "http://linkedin.com/in/disha-nannaware-074883319",
    githubUrl: "",
  },


// DATABASE TEAM
  {
    id: 22,
    name: "Anshu Vairagade",
    position: "DATABASE HEAD",
    imageUrl: "https://drive.google.com/open?id=1faMoyDw0UMzqy6MGFAjcVX8eNIVbDbyq",
    instagramUrl: "",
    linkedinUrl: "http://www.linkedin.com/in/anshuvairagade",
    githubUrl: "https://github.com/AnshuVairagade",
  },
  {
    id: 23,
    name: "Abhang Kolte",
    position: "DATABASE HEAD",
    imageUrl: "https://drive.google.com/open?id=14-cylwCAgfi1sYKLvdOAgKDcHaLhJeOp",
    instagramUrl: "",
    linkedinUrl: "http://linkedin.com/in/abhang-kolte-a16897281",
    githubUrl: "",
  },
  {
    id: 24,
    name: "Shreya Kashyap",
    position: "DATABASE HEAD",
    imageUrl: "https://drive.google.com/open?id=1nXtxUt2j-ZngKHBIeq8x2675O3Up3237",
    instagramUrl: "https://www.instagram.com/shreya__.kashyap/?next=%2F",
    linkedinUrl: "http://linkedin.com/in/shreya-kashyap3537",
    githubUrl: "",
  },
    {
    id: 44,
    name: "Bhawana Nirwan",
    position: "DATABASE CO-HEAD",
    imageUrl:"https://drive.google.com/open?id=1CHELBJo11EXykcg6DMcM156VnBvnrXm7",
    instagramUrl: "https://www.instagram.com/ask_bhhavanaa_?igsh=cnczbzJ5bzE2cDQ5",
    linkedinUrl: "https://www.linkedin.com/in/bhawana-nirwan",
    githubUrl: "",
  },
  {
    id: 60,
    name: "Shaki Gajbhiye",
    position: "DATABASE MEMBER",
    imageUrl: "https://drive.google.com/open?id=11LyM3VMNTvolvUNMC1ghWYzP8RUBNNzW",
    instagramUrl: "https://www.instagram.com/shakigajbhiye?igsh=Y290NW1wcXg0YWtw",
    linkedinUrl: "https://www.linkedin.com/in/shaki-gajbhiye?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    githubUrl: "https://github.com/Shaki-2005",
  },
  //PHOTOGRAPHY TEAM
    {
    id: 68,
    name: "Jatin Mahajan",
    position: "PHOTOGRAPHY HEAD",
    imageUrl: "https://drive.google.com/open?id=1bkRgSHe9n-6-jvea2gxtHgOMWYJ6vVHW",
    instagramUrl: "https://www.instagram.com/_jatin.mahajan_",
    linkedinUrl: "https://www.linkedin.com/in/jatin-mahajan",
    githubUrl: "",
  },  {
    id: 69,
    name: "Krushnangi Manekar",
    position: "PHOTOGRAPHY HEAD",
    imageUrl:"https://drive.google.com/open?id=14KZR44NWlGoeLwMKvghl3wItLOkPjNUx",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/krushnangi-manekar",
    githubUrl: "https://github.com/Krushnangi",
  },
   {
    id: 52,
    name: "Shreeyash Dhale",
    position: "PHOTOGRAPHY CO-HEAD",
    imageUrl:"https://drive.google.com/open?id=1_i28BdXc8xOmPwHegdC8lkgIPUqbjoDK",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/shreeyash-dhale-249a1b2b9",
    githubUrl: "",
  },


  // SPORTS TEAM

  {
    id: 36,
    name: "Kshitij Shrikhande",
    position: "SPORTS HEAD",
    imageUrl: "https://drive.google.com/open?id=1rLhlmUfS9xKnoedCRla04UmmmUntRGM0",
    instagramUrl: "",
    linkedinUrl: "https://www.linkedin.com/in/kshitij-shrikhande",
    githubUrl: "",
  },
   {
    id: 55,
    name: "Omair Khan",
    position: "SPORTS CO-HEAD",
    imageUrl: "https://drive.google.com/open?id=1IqGXUDFs-lZ5PHckUYH5WRonL3jJaRfZ",
    instagramUrl: "https://www.instagram.com/omair.586/",
    linkedinUrl: "https://www.linkedin.com/in/omair-ahmad-khan-383621345/",
    githubUrl: "https://github.com/OmairKhan29",
  }
];
